# Global
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: 'honeypots-monitor'

# Scrape configs
scrape_configs:
  - job_name: 'prometheus'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    scheme: https
    follow_redirects: true
    static_configs:
      - targets:
          - 'host.docker.internal:8090'