# Spring settings
spring:

  # Datasource
  datasource:
    url: jdbc:h2:mem:honeypot;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8
    schema: classpath:db/h2/${spring.profiles.active}/schema*.sql
    data: classpath:db/h2/${spring.profiles.active}/data*.sql

  # H2
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  # Console Output
  output:
    ansi:
      enabled: always

  # MVC
  mvc:
    log-request-details: true

# Logging settings
logging:
  level:
    root: info
    com:
      honeypot: debug
    org:
      springframework:
        web: trace

# OAuth
oauth:
  kakao:
    client-secret: lDDWMiLlahtpdtKCgR04mlUCFvGsXbhV
    redirect-url: "http://localhost:8090/api/auth/kakao"
    api-key:
      rest-api: 211dafc4f98802b4890c43ec2b305f72
      admin: 3a032aeb8d68e14d7d99c7172142911a
    api-path:
      get-auth-code: "https://kauth.kakao.com/oauth/authorize"
      get-access-token: "https://kauth.kakao.com/oauth/token"
      get-access-token-info: "https://kapi.kakao.com/v1/user/access_token_info"
      get-userinfo-by-access-token: "https://kapi.kakao.com/v2/user/me"
    user-property:
      profile: "kakao_account.profile"
      name: "kakao_account.name"
      email: "kakao_account.email"
      age-range: "kakao_account.age_range"
      birthday: "kakao_account.birthday"
      gender: "kakao_account.gender"