# Spring settings
spring:
  datasource:
    url: jdbc:h2:mem:honeypot;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8
    schema: classpath:db/h2/${spring.profiles.active}/schema*.sql
    data: classpath:db/h2/${spring.profiles.active}/data*.sql
  h2:
    console:
      enabled: true
      path: /h2-console

# Logging settings
logging:
  level:
    root: info